### ISSUE TITLE
More detail in pagination/loop of articles

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#3]
<img width="828" alt="Screenshot 2023-08-03 at 16 05 57" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/c9dbf070-2dbb-49ba-a226-4a4ef01711ea">

Show more detail about the article below the title

Handlebars file is partials/loop.hbs

For accessibility:
- the post title should use a header class (eg h3). Any further content should not
- Links shouldn't be repeated, i.e. a link on the h3, a link on the tag, not more
- if showing thumbnail, should use the alt text

### Tasks
- [ ] Add primary tag, eg. climate, news, etc
- [ ] add excerpt
- [ ] make title bold to stand out from excerpt
- [ ] if article has feature image, to show thumbnail of feature image

**Comment by cathysarisky** [comment]
Can do.  If you have thoughts on how you want it to look, please share.  Otherwise I'll be happy to make something up, but it may take us a couple rounds to make it look right.
(It doesn't have to be a GOOD mockup - even a photo of a scribbled version, or something you assembled in Paint is great.  I just want to see where you are envisioning these elements being relative to each other.)

**Comment by peterfremlin** [comment]
Ahaha well here is what I was thinking - do you think would work visually?

![pagination preview](https://github.com/peterfremlin/Disability-Debrief/assets/106767665/a8a7d3ef-25be-490f-9942-307acf8cf740)

**Comment by cathysarisky** [comment]
preview:
![image](https://github.com/peterfremlin/Disability-Debrief/assets/42299862/de8d8b53-afcb-4748-acfe-e4aae68d7f99)

**Comment by cathysarisky** [comment]
(broken images are just a problem with the import, not the theme.)

**Comment by peterfremlin** [comment]
Love this, it looks great, well done!
Seeing the result I see that the tag is unnecessary and kinda distracting - can you remove that please?

**Comment by cathysarisky** [comment]
Sure thing!

**Comment by cathysarisky** [comment]
Done.

**Comment by peterfremlin** [comment]
Looks great and appreciate the margin adjust. Will need to do an access check and get back.
